blank_issues_enabled: false
contact_links:
  - name: 💬 Dúvidas gerais
    url: https://github.com/guilhermelimatech/setup-senior-pro/discussions
    about: Use Discussions para perguntas e ideias abertas.
